
title: Organização e Apresentação de Dados
description: Departamento de Estatística - UFLA.
theme: jekyll-theme-architect
gem "github-pages", group: :jekyll_plugins

styles:
  - "/assets/custom.css"

#Others
markdown: kramdown
