
title: Organização e Apresentação de Dados (GES109)
description: Departamento de Estatística - UFLA.
theme: jekyll-theme-architect
gem "github-pages", group: :jekyll_plugins

#Others
markdown: kramdown
