
title: Organização e Apresentação de Dados
description: Departamento de Estatística - UFLA.
theme: jekyll-theme-architect
gem "github-pages", group: :jekyll_plugins

sass:
  sass_dir: _sass
  style: compressed
  custom_style: |
    body {
      background-color: #f0f0f0; /* Cor de fundo do corpo */
      color: #333; /* Cor do texto principal */
    }

    h1 {
      color: #0066cc; /* Cor do título H1 */
    }
